name: abc
on: push
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - name: Create Check Run
      id: create_check_run
      run: |
          response=$(curl -X POST \
            -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" \
            -H "Accept: application/vnd.github.v3+json" \
            https://api.github.com/repos/${{ github.repository }}/check-runs \
            -d '{
              "name": "Ping Google for fun",
              "head_sha": "${{ github.sha }}",
              "status": "in_progress"
            }')
          check_run_id=$(echo "$response" | jq -r .id)
          echo "Check Run ID: $check_run_id"
          echo "check_run_id=$check_run_id" >> $GITHUB_ENV
